### ISSUE TITLE
Add tag to collection if doesn't exist?

### ISSUE THREAD

**Issue by brylie** [yogiben/meteor-autoform-tags-toggle#2]
Is there a simple recipe to add a tag to a 'tags' collection if it doesn't exist? E.g. the user enters one or more tags. Each time return is pressed, the tags collection is queried and a new tag is added if it didn't exist.

**Comment by yogiben** [comment]
See https://github.com/yogiben/meteor-autoform-tags

**Comment by brylie** [comment]
Thanks @yogiben :-)
